#!/bin/bash

set -u
set -e

SERVICE_INSTANCE_NAME="$(systemctl list-units -t service --all | grep webilastik@ | head -n 1 | awk '{print $1}')"

systemctl stop "$SERVICE_INSTANCE_NAME"
systemctl disable webilastik@.service