"""
This type stub file was generated by pyright.
"""

from __future__ import absolute_import

"""
    This subpackage implements the high-level interface for h5py.

    Don't manually import things from here; the public API lives directly
    in the top-level package namespace.
"""
