"""
This type stub file was generated by pyright.
"""

from typing import Any
from . import base
from .base import with_phil

import numpy as np

"""
    Implements high-level opera"""
class AttributeManager(base.MutableMappingHDF5, base.CommonStateObject):
    """
        Allows dictionary-style"""
    def __init__(self, parent) -> None:
        """ Private constructor.
        """
        ...

    # @with_phil
    def __getitem__(self, name: str) -> "np.ndarray[Any, Any] | str | np.int64 | np.float64":
        """ Read the value of an attribute."""
        ...

    def get_id(self, name: str):
        """Get a low-level AttrID object fo"""
        ...

    @with_phil
    def __setitem__(self, name, value): # -> None:
        """ Set a new attribute, overwritin"""
        ...

    @with_phil
    def __delitem__(self, name): # -> None:
        """ Delete an attribute (which must"""
        ...

    def create(self, name, data, shape=..., dtype=...):
        """ Create a new attribute, overwri"""
        ...

    def modify(self, name, value): # -> None:
        """ Change the value of an attribut"""
        ...

    @with_phil
    def __len__(self):
        """ Number of attributes attached t"""
        ...

    def __iter__(self): # -> Generator[Unknown, None, None]:
        """ Iterate over the names of attri"""
        ...

    @with_phil
    def __contains__(self, name):
        """ Determine if an attribute exist"""
        ...

    @with_phil
    def __repr__(self): # -> str:
        ...



