"""
This type stub file was generated by pyright.
"""

"""
Compatibility module for high-l"""
WINDOWS_ENCODING = ...
def filename_encode(filename): # -> bytes:
    """
    Encode filename for use in """
    ...

def filename_decode(filename): # -> str:
    """
    Decode filename used by HDF"""
    ...

