"""
This type stub file was generated by pyright.
"""

import six
from .base import with_phil
from .group import Group
from .. import h5, h5f, version

"""
    Implements high-level support for HDF5 file objects.
"""
mpi = h5.get_config().mpi
hdf5_version = version.hdf5_version_tuple[0: 3]
swmr_support = False
if hdf5_version >= h5.get_config().swmr_min_hdf5_version:
    swmr_support = True
libver_dict = { 'earliest': h5f.LIBVER_EARLIEST,'latest': h5f.LIBVER_LATEST }
libver_dict_r = dict((y, x) for (x, y) in six.iteritems(libver_dict))
if hdf5_version >= (1, 10, 2):
    ...
_drivers = { 'sec2': lambda plist, **kwargs: plist.set_fapl_sec2(**kwargs),'stdio': lambda plist, **kwargs: plist.set_fapl_stdio(**kwargs),'core': lambda plist, **kwargs: plist.set_fapl_core(**kwargs),'family': lambda plist, **kwargs: plist.set_fapl_family(memb_fapl=plist.copy(), **kwargs),'mpio': _set_fapl_mpio,'fileobj': _set_fapl_fileobj }
def register_driver(name, set_fapl):
    """Register a custom driver.

    Parameters
    ----------
    name : str
        The name of the driver.
    set_fapl : callable[PropFAID, **kwargs] -> NoneType
        The function to set the fapl to use your custom driver.
    """
    ...

def unregister_driver(name):
    """Unregister a custom driver.

    Parameters
    ----------
    name : str
        The name of the driver.
    """
    ...

def registered_drivers():
    """Return a frozenset of the names of all of the registered drivers.
    """
    ...

def make_fapl(driver, libver, rdcc_nslots, rdcc_nbytes, rdcc_w0, **kwds):
    """ Set up a file access property list """
    ...

def make_fcpl(track_order=...):
    """ Set up a file creation property list """
    ...

def make_fid(name, mode, userblock_size, fapl, fcpl=..., swmr=...):
    """ Get a new FileID by opening or creating a file.
    Also validates mode argument."""
    ...

class File(Group):
    """
        Represents an HDF5 file.
    """
    @property
    def attrs(self):
        """ Attributes attached to this object """
        ...

    @property
    @with_phil
    def filename(self) -> str:
        """File name on disk"""
        ...

    @property
    @with_phil
    def driver(self):
        """Low-level HDF5 file driver used to open file"""
        ...

    @property
    @with_phil
    def mode(self):
        """ Python mode used to open file """
        ...

    @property
    @with_phil
    def fid(self):
        """File ID (backwards compatibility) """
        ...

    @property
    @with_phil
    def libver(self):
        """File format version bounds (2-tuple: low, high)"""
        ...

    @property
    @with_phil
    def userblock_size(self):
        """ User block size (in bytes) """
        ...

    if mpi and hdf5_version >= (1, 8, 9):
        @property
        @with_phil
        def atomic(self):
            """ Set/get MPI-IO atomic mode
            """
            ...

        @atomic.setter
        @with_phil
        def atomic(self, value):
            ...

    if swmr_support:
        @property
        def swmr_mode(self):
            """ Controls single-writer multiple-reader mode """
            ...

        @swmr_mode.setter
        @with_phil
        def swmr_mode(self, value):
            ...

    def __init__(self, name, mode=..., driver=..., libver=..., userblock_size=..., swmr=..., rdcc_nslots=..., rdcc_nbytes=..., rdcc_w0=..., track_order=..., **kwds) -> None:
        """Create a new file object.

        See the h5py user guide for a detailed explanation of the options.

        name
            Name of the file on disk, or file-like object.  Note: for files
            created with the 'core' driver, HDF5 still requires this be
            non-empty.
        mode
            r        Readonly, file must exist
            r+       Read/write, file must exist
            w        Create file, truncate if exists
            w- or x  Create file, fail if exists
            a        Read/write if exists, create otherwise (default)
        driver
            Name of the driver to use.  Legal values are None (default,
            recommended), 'core', 'sec2', 'stdio', 'mpio'.
        libver
            Library version bounds.  Supported values: 'earliest', 'v108',
            'v110',  and 'latest'. The 'v108' and 'v110' options can only be
            specified with the HDF5 1.10.2 library or later.
        userblock
            Desired size of user block.  Only allowed when creating a new
            file (mode w, w- or x).
        swmr
            Open the file in SWMR read mode. Only used when mode = 'r'.
        rdcc_nbytes
            Total size of the raw data chunk cache in bytes. The default size
            is 1024**2 (1 MB) per dataset.
        rdcc_w0
            The chunk preemption policy for all datasets.  This must be
            between 0 and 1 inclusive and indicates the weighting according to
            which chunks which have been fully read or written are penalized
            when determining which chunks to flush from cache.  A value of 0
            means fully read or written chunks are treated no differently than
            other chunks (the preemption is strictly LRU) while a value of 1
            means fully read or written chunks are always preempted before
            other chunks.  If your application only reads or writes data once,
            this can be safely set to 1.  Otherwise, this should be set lower
            depending on how often you re-read or re-write the same data.  The
            default value is 0.75.
        rdcc_nslots
            The number of chunk slots in the raw data chunk cache for this
            file. Increasing this value reduces the number of cache collisions,
            but slightly increases the memory used. Due to the hashing
            strategy, this value should ideally be a prime number. As a rule of
            thumb, this value should be at least 10 times the number of chunks
            that can fit in rdcc_nbytes bytes. For maximum performance, this
            value should be set approximately 100 times that number of
            chunks. The default value is 521.
        track_order
            Track dataset/group/attribute creation order under root group
            if True. If None use global default h5.get_config().track_order.
        Additional keywords
            Passed on to the selected file driver.

        """
        ...

    def close(self) -> None:
        """ Close the file.  All open objects become invalid """
        ...

    def flush(self):
        """ Tell the HDF5 library to flush its buffers.
        """
        ...

    @with_phil
    def __enter__(self) -> "File":
        ...

    @with_phil
    def __exit__(self, *args):
        ...

    @with_phil
    def __repr__(self):
        ...
