"""
This type stub file was generated by pyright.
"""

"""
    Implements a portion of the"""
def read_dtypes(dataset_dtype, names): # -> tuple[Unknown | dtype[Any] | dtype[void], Unknown | dtype[void]]:
    """ Returns a 2-tuple containing:

"""
    ...

def read_selections_scalar(dsid, args): # -> tuple[tuple[()] | None, Unknown]:
    """ Returns a 2-tuple containing:

"""
    ...

class ScalarReadSelection:
    """
        Implements slicing for """
    def __init__(self, fspace, args) -> None:
        ...
    
    def __iter__(self): # -> Generator[tuple[Unknown, Unknown], None, None]:
        ...
    


def select_read(fspace, args): # -> ScalarReadSelection:
    """ Top-level dispatch function for"""
    ...

