"""
This type stub file was generated by pyright.
"""

from collections import namedtuple
from .. import h5

"""
    High-level interface for cr"""
class VDSmap(namedtuple('VDSmap', ('vspace', 'file_name', 'dset_name', 'src_space'))):
    '''Defines a region in a virtual da'''
    ...


vds_support = ...
hdf5_version = ...
if hdf5_version >= h5.get_config().vds_min_hdf5_version:
    vds_support = ...
class VirtualSource:
    """Source definition for virtual da"""
    def __init__(self, path_or_dataset, name=..., shape=..., dtype=..., maxshape=...) -> None:
        ...
    
    @property
    def shape(self): # -> tuple[Unknown, ...]:
        ...
    
    def __getitem__(self, key): # -> Self@VirtualSource:
        ...
    


class VirtualLayout:
    """Object for building a virtual da"""
    def __init__(self, shape, dtype, maxshape=..., filename=...) -> None:
        ...
    
    def __setitem__(self, key, source): # -> None:
        ...
    
    def make_dataset(self, parent, name, fillvalue=...):
        """ Return a new low-level dataset """
        ...
    


