"""
This type stub file was generated by pyright.
"""

"""
    This module contains the warning classes for h5py. These classes are part of
    the public API of h5py, and should be imported from this module.
"""
class H5pyWarning(UserWarning):
    ...


class H5pyDeprecationWarning(H5pyWarning):
    ...


class ModuleWrapper(object):
    def __init__(self, mod) -> None:
        ...
    
    def __getattr__(self, attr):
        ...
    


