"""
This type stub file was generated by pyright.
"""

"""
    This is the deprecated legacy high-level interface.

    Everything here is canonically located at the root of the package.
    New code should import directly from there, e.g. "from h5py import File".
"""
