"""
This type stub file was generated by pyright.
"""

"""
    This is the h5py completer """
re_attr_match = ...
re_item_match = ...
re_object_match = ...
def h5py_item_completer(context, command):
    """Compute possible item matches fo"""
    ...

def h5py_attr_completer(context, command):
    """Compute possible attr matches fo"""
    ...

def h5py_completer(self, event): # -> list[Unknown]:
    """ Completer function to be loaded"""
    ...

def load_ipython_extension(ip=...): # -> None:
    """ Load completer function into IP"""
    ...

