def angularGaborSigma(*args, **kwargs) -> Any: ...
def createGaborFilter(*args, **kwargs) -> Any: ...
def fourierTransform(*args, **kwargs) -> Any: ...
def fourierTransformInverse(*args, **kwargs) -> Any: ...
def radialGaborSigma(*args, **kwargs) -> Any: ...
