import Boost.Python
INVALID: Any
agglomerativeClustering: Any
edgeWeightedWatersheds: Any
felzenszwalbSegmentation: Any
getEdgeLengths: Any
getNodeSizes: Any
graphMap: Any
gridGraph: Any
gridRegionAdjacencyGraph: Any
hierarchicalClustering: Any
intrinsicGraphMapShape: Any
isGridGraph: Any
isGridGraph2d: Any
listGraph: Any
loadGridRagHDF5: Any
mergeGraph: Any
minEdgeWeightNodeDist: Any
nodeFeaturesToEdgeWeights: Any
nodeWeightedWatersheds: Any
nodeWeightedWatershedsSeeds: Any
pythonClusterOperator: Any
recursiveGraphSmoothing: Any
regionAdjacencyGraph: Any
seededSegmentation: Any
shortestPathSegmentation: Any

def __hierarchicalClustering(*args, **kwargs) -> Any: ...
def __mergeGraph(*args, **kwargs) -> Any: ...
def __minEdgeWeightNodeDistOperator(*args, **kwargs) -> Any: ...
def __pythonClusterOperator(*args, **kwargs) -> Any: ...
def _carvingSegmentation(*args, **kwargs) -> Any: ...
def _deserialzieGridGraphAffiliatedEdges(*args, **kwargs) -> Any: ...
def _edgeWeightedWatershedsSegmentation(*args, **kwargs) -> Any: ...
def _felzenszwalbSegmentation(*args, **kwargs) -> Any: ...
def _nodeFeatureDistToEdgeWeight(*args, **kwargs) -> Any: ...
def _nodeFeatureSumToEdgeWeight(*args, **kwargs) -> Any: ...
def _nodeWeightedWatershedsSeeds(*args, **kwargs) -> Any: ...
def _nodeWeightedWatershedsSegmentation(*args, **kwargs) -> Any: ...
def _opengmArgToLabeling(*args, **kwargs) -> Any: ...
def _opengmMulticutDataStructure(*args, **kwargs) -> Any: ...
def _pyAccNodeSeeds(*args, **kwargs) -> Any: ...
def _ragEdgeFeatures(*args, **kwargs) -> Any: ...
def _ragEdgeFeaturesMb(*args, **kwargs) -> Any: ...
def _ragEdgeSize(*args, **kwargs) -> Any: ...
def _ragEdgeStatistics(*args, **kwargs) -> Any: ...
def _ragFindEdges(*args, **kwargs) -> Any: ...
def _ragNodeFeatures(*args, **kwargs) -> Any: ...
def _ragNodeSize(*args, **kwargs) -> Any: ...
def _ragProjectGroundTruth(*args, **kwargs) -> Any: ...
def _ragProjectNodeFeaturesToBaseGraph(*args, **kwargs) -> Any: ...
def _recursiveGraphSmoothing(*args, **kwargs) -> Any: ...
def _regionAdjacencyGraph(*args, **kwargs) -> Any: ...
def _serialzieGridGraphAffiliatedEdges(*args, **kwargs) -> Any: ...
def _shortestPathDijkstra(*args, **kwargs) -> Any: ...
def _shortestPathSegmentation(*args, **kwargs) -> Any: ...
def _wardCorrection(*args, **kwargs) -> Any: ...
def cyclesEdges(*args, **kwargs) -> Any: ...
def edgeFeaturesFromImage(*args, **kwargs) -> Any: ...
def edgeFeaturesFromInterpolatedImage(*args, **kwargs) -> Any: ...
def find3Cycles(*args, **kwargs) -> Any: ...
def find3CyclesEdges(*args, **kwargs) -> Any: ...
def implicitMeanEdgeMap(*args, **kwargs) -> Any: ...
def nodeGtToEdgeGt(*args, **kwargs) -> Any: ...

class AdjacencyListGraph(Boost.Python.instance):
    __instance_size__: Any = ...
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def addEdge(self, *args, **kwargs) -> Any: ...
    @classmethod
    def addEdges(self, *args, **kwargs) -> Any: ...
    @classmethod
    def addNode(self, *args, **kwargs) -> Any: ...
    @classmethod
    def arcFromId(self, *args, **kwargs) -> Any: ...
    @classmethod
    def arcIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def axistagsArcMap(self, *args, **kwargs) -> Any: ...
    @classmethod
    def axistagsEdgeMap(self, *args, **kwargs) -> Any: ...
    @classmethod
    def axistagsNodeMap(self, *args, **kwargs) -> Any: ...
    @classmethod
    def deserialize(self, *args, **kwargs) -> Any: ...
    @classmethod
    def edgeFromArc(self, *args, **kwargs) -> Any: ...
    @classmethod
    def edgeFromId(self, *args, **kwargs) -> Any: ...
    @classmethod
    def edgeIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def edgeIter(self, *args, **kwargs) -> Any: ...
    @classmethod
    def findEdge(self, *args, **kwargs) -> Any: ...
    @classmethod
    def findEdges(self, *args, **kwargs) -> Any: ...
    @classmethod
    def id(self, *args, **kwargs) -> Any: ...
    @classmethod
    def incEdgeIter(self, *args, **kwargs) -> Any: ...
    @classmethod
    def intrinsicArcCoordinate(self, *args, **kwargs) -> Any: ...
    @classmethod
    def intrinsicArcMapShape(self, *args, **kwargs) -> Any: ...
    @classmethod
    def intrinsicEdgeCoordinate(self, *args, **kwargs) -> Any: ...
    @classmethod
    def intrinsicEdgeMapShape(self, *args, **kwargs) -> Any: ...
    @classmethod
    def intrinsicNodeCoordinate(self, *args, **kwargs) -> Any: ...
    @classmethod
    def intrinsicNodeMapShape(self, *args, **kwargs) -> Any: ...
    @classmethod
    def neighbourNodeIter(self, *args, **kwargs) -> Any: ...
    @classmethod
    def nodeFromId(self, *args, **kwargs) -> Any: ...
    @classmethod
    def nodeIdMap(self, *args, **kwargs) -> Any: ...
    @classmethod
    def nodeIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def nodeIter(self, *args, **kwargs) -> Any: ...
    @classmethod
    def serializationSize(self, *args, **kwargs) -> Any: ...
    @classmethod
    def serialize(self, *args, **kwargs) -> Any: ...
    @classmethod
    def source(self, *args, **kwargs) -> Any: ...
    @classmethod
    def target(self, *args, **kwargs) -> Any: ...
    @classmethod
    def u(self, *args, **kwargs) -> Any: ...
    @classmethod
    def uId(self, *args, **kwargs) -> Any: ...
    @classmethod
    def uIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def uvId(self, *args, **kwargs) -> Any: ...
    @classmethod
    def uvIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def v(self, *args, **kwargs) -> Any: ...
    @classmethod
    def vId(self, *args, **kwargs) -> Any: ...
    @classmethod
    def vIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def validArcIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def validEdgeIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def validNodeIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def __len__(self) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...
    @property
    def arcNum(self) -> Any: ...
    @property
    def edgeNum(self) -> Any: ...
    @property
    def maxArcId(self) -> Any: ...
    @property
    def maxEdgeId(self) -> Any: ...
    @property
    def maxNodeId(self) -> Any: ...
    @property
    def nodeNum(self) -> Any: ...

class AdjacencyListGraphMergeGraph(Boost.Python.instance):
    __instance_size__: Any = ...
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def arcFromId(self, *args, **kwargs) -> Any: ...
    @classmethod
    def arcIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def axistagsArcMap(self, *args, **kwargs) -> Any: ...
    @classmethod
    def axistagsEdgeMap(self, *args, **kwargs) -> Any: ...
    @classmethod
    def axistagsNodeMap(self, *args, **kwargs) -> Any: ...
    @classmethod
    def contractEdge(self, *args, **kwargs) -> Any: ...
    @classmethod
    def edgeFromArc(self, *args, **kwargs) -> Any: ...
    @classmethod
    def edgeFromId(self, *args, **kwargs) -> Any: ...
    @classmethod
    def edgeIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def edgeIter(self, *args, **kwargs) -> Any: ...
    @classmethod
    def findEdge(self, *args, **kwargs) -> Any: ...
    @classmethod
    def findEdges(self, *args, **kwargs) -> Any: ...
    @classmethod
    def graph(self, *args, **kwargs) -> Any: ...
    @classmethod
    def graphLabels(self, *args, **kwargs) -> Any: ...
    @classmethod
    def hasEdgeId(self, *args, **kwargs) -> Any: ...
    @classmethod
    def id(self, *args, **kwargs) -> Any: ...
    @classmethod
    def inactiveEdgesNode(self, *args, **kwargs) -> Any: ...
    @classmethod
    def incEdgeIter(self, *args, **kwargs) -> Any: ...
    @classmethod
    def intrinsicArcCoordinate(self, *args, **kwargs) -> Any: ...
    @classmethod
    def intrinsicArcMapShape(self, *args, **kwargs) -> Any: ...
    @classmethod
    def intrinsicEdgeCoordinate(self, *args, **kwargs) -> Any: ...
    @classmethod
    def intrinsicEdgeMapShape(self, *args, **kwargs) -> Any: ...
    @classmethod
    def intrinsicNodeCoordinate(self, *args, **kwargs) -> Any: ...
    @classmethod
    def intrinsicNodeMapShape(self, *args, **kwargs) -> Any: ...
    @classmethod
    def neighbourNodeIter(self, *args, **kwargs) -> Any: ...
    @classmethod
    def nodeFromId(self, *args, **kwargs) -> Any: ...
    @classmethod
    def nodeIdMap(self, *args, **kwargs) -> Any: ...
    @classmethod
    def nodeIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def nodeIter(self, *args, **kwargs) -> Any: ...
    @classmethod
    def source(self, *args, **kwargs) -> Any: ...
    @classmethod
    def target(self, *args, **kwargs) -> Any: ...
    @classmethod
    def u(self, *args, **kwargs) -> Any: ...
    @classmethod
    def uId(self, *args, **kwargs) -> Any: ...
    @classmethod
    def uIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def uvId(self, *args, **kwargs) -> Any: ...
    @classmethod
    def uvIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def v(self, *args, **kwargs) -> Any: ...
    @classmethod
    def vId(self, *args, **kwargs) -> Any: ...
    @classmethod
    def vIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def validArcIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def validEdgeIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def validNodeIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def __len__(self) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...
    @property
    def arcNum(self) -> Any: ...
    @property
    def edgeNum(self) -> Any: ...
    @property
    def maxArcId(self) -> Any: ...
    @property
    def maxEdgeId(self) -> Any: ...
    @property
    def maxNodeId(self) -> Any: ...
    @property
    def nodeNum(self) -> Any: ...

class AdjacencyListGraphMergeGraphMinEdgeWeightNodeDistOperator(Boost.Python.instance):
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def enableStopWeight(self, *args, **kwargs) -> Any: ...
    @classmethod
    def setLiftedEdges(self, *args, **kwargs) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...

class AdjacencyListGraphMergeGraphPythonOperator(Boost.Python.instance):
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def __reduce__(self) -> Any: ...

class AdjacencyListGraphRagAffiliatedEdges(Boost.Python.instance):
    __instance_size__: Any = ...
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def getUVCoordinates(self, *args, **kwargs) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...

class ArcAdjacencyListGraph(Boost.Python.instance):
    __instance_size__: Any = ...
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def coord(self, *args, **kwargs) -> Any: ...
    @classmethod
    def __eq__(self, other) -> Any: ...
    @classmethod
    def __ne__(self, other) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...
    @property
    def id(self) -> Any: ...

class ArcAdjacencyListGraphMergeGraph(Boost.Python.instance):
    __instance_size__: Any = ...
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def coord(self, *args, **kwargs) -> Any: ...
    @classmethod
    def __eq__(self, other) -> Any: ...
    @classmethod
    def __ne__(self, other) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...
    @property
    def id(self) -> Any: ...

class ArcGridGraphUndirected2d(Boost.Python.instance):
    __instance_size__: Any = ...
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def coord(self, *args, **kwargs) -> Any: ...
    @classmethod
    def __eq__(self, other) -> Any: ...
    @classmethod
    def __ne__(self, other) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...
    @property
    def id(self) -> Any: ...

class ArcGridGraphUndirected2dMergeGraph(Boost.Python.instance):
    __instance_size__: Any = ...
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def coord(self, *args, **kwargs) -> Any: ...
    @classmethod
    def __eq__(self, other) -> Any: ...
    @classmethod
    def __ne__(self, other) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...
    @property
    def id(self) -> Any: ...

class ArcGridGraphUndirected3d(Boost.Python.instance):
    __instance_size__: Any = ...
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def coord(self, *args, **kwargs) -> Any: ...
    @classmethod
    def __eq__(self, other) -> Any: ...
    @classmethod
    def __ne__(self, other) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...
    @property
    def id(self) -> Any: ...

class ArcGridGraphUndirected3dMergeGraph(Boost.Python.instance):
    __instance_size__: Any = ...
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def coord(self, *args, **kwargs) -> Any: ...
    @classmethod
    def __eq__(self, other) -> Any: ...
    @classmethod
    def __ne__(self, other) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...
    @property
    def id(self) -> Any: ...

class EdgeAdjacencyListGraph(Boost.Python.instance):
    __instance_size__: Any = ...
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def coord(self, *args, **kwargs) -> Any: ...
    @classmethod
    def __eq__(self, other) -> Any: ...
    @classmethod
    def __ne__(self, other) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...
    @property
    def id(self) -> Any: ...
    @property
    def u(self) -> Any: ...
    @property
    def v(self) -> Any: ...

class EdgeAdjacencyListGraphMergeGraph(Boost.Python.instance):
    __instance_size__: Any = ...
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def coord(self, *args, **kwargs) -> Any: ...
    @classmethod
    def __eq__(self, other) -> Any: ...
    @classmethod
    def __ne__(self, other) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...
    @property
    def id(self) -> Any: ...
    @property
    def u(self) -> Any: ...
    @property
    def v(self) -> Any: ...

class EdgeGridGraphUndirected2d(Boost.Python.instance):
    __instance_size__: Any = ...
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def coord(self, *args, **kwargs) -> Any: ...
    @classmethod
    def __eq__(self, other) -> Any: ...
    @classmethod
    def __ne__(self, other) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...
    @property
    def id(self) -> Any: ...
    @property
    def u(self) -> Any: ...
    @property
    def v(self) -> Any: ...

class EdgeGridGraphUndirected2dMergeGraph(Boost.Python.instance):
    __instance_size__: Any = ...
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def coord(self, *args, **kwargs) -> Any: ...
    @classmethod
    def __eq__(self, other) -> Any: ...
    @classmethod
    def __ne__(self, other) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...
    @property
    def id(self) -> Any: ...
    @property
    def u(self) -> Any: ...
    @property
    def v(self) -> Any: ...

class EdgeGridGraphUndirected3d(Boost.Python.instance):
    __instance_size__: Any = ...
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def coord(self, *args, **kwargs) -> Any: ...
    @classmethod
    def __eq__(self, other) -> Any: ...
    @classmethod
    def __ne__(self, other) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...
    @property
    def id(self) -> Any: ...
    @property
    def u(self) -> Any: ...
    @property
    def v(self) -> Any: ...

class EdgeGridGraphUndirected3dMergeGraph(Boost.Python.instance):
    __instance_size__: Any = ...
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def coord(self, *args, **kwargs) -> Any: ...
    @classmethod
    def __eq__(self, other) -> Any: ...
    @classmethod
    def __ne__(self, other) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...
    @property
    def id(self) -> Any: ...
    @property
    def u(self) -> Any: ...
    @property
    def v(self) -> Any: ...

class EdgeIteratorHolderAdjacencyListGraph(Boost.Python.instance):
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def __iter__(self) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...

class EdgeIteratorHolderAdjacencyListGraphMergeGraph(Boost.Python.instance):
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def __iter__(self) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...

class EdgeIteratorHolderGridGraphUndirected2d(Boost.Python.instance):
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def __iter__(self) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...

class EdgeIteratorHolderGridGraphUndirected2dMergeGraph(Boost.Python.instance):
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def __iter__(self) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...

class EdgeIteratorHolderGridGraphUndirected3d(Boost.Python.instance):
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def __iter__(self) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...

class EdgeIteratorHolderGridGraphUndirected3dMergeGraph(Boost.Python.instance):
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def __iter__(self) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...

class EdgeVectorAdjacencyListGraph(Boost.Python.instance):
    __instance_size__: Any = ...
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def append(self, *args, **kwargs) -> Any: ...
    @classmethod
    def extend(self, *args, **kwargs) -> Any: ...
    @classmethod
    def __contains__(self, other) -> Any: ...
    @classmethod
    def __delitem__(self, other) -> Any: ...
    @classmethod
    def __getitem__(self, index) -> Any: ...
    @classmethod
    def __iter__(self) -> Any: ...
    @classmethod
    def __len__(self) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...
    @classmethod
    def __setitem__(self, index, object) -> Any: ...

class EdgeVectorAdjacencyListGraphMergeGraph(Boost.Python.instance):
    __instance_size__: Any = ...
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def append(self, *args, **kwargs) -> Any: ...
    @classmethod
    def extend(self, *args, **kwargs) -> Any: ...
    @classmethod
    def __contains__(self, other) -> Any: ...
    @classmethod
    def __delitem__(self, other) -> Any: ...
    @classmethod
    def __getitem__(self, index) -> Any: ...
    @classmethod
    def __iter__(self) -> Any: ...
    @classmethod
    def __len__(self) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...
    @classmethod
    def __setitem__(self, index, object) -> Any: ...

class EdgeVectorGridGraphUndirected2d(Boost.Python.instance):
    __instance_size__: Any = ...
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def append(self, *args, **kwargs) -> Any: ...
    @classmethod
    def extend(self, *args, **kwargs) -> Any: ...
    @classmethod
    def __contains__(self, other) -> Any: ...
    @classmethod
    def __delitem__(self, other) -> Any: ...
    @classmethod
    def __getitem__(self, index) -> Any: ...
    @classmethod
    def __iter__(self) -> Any: ...
    @classmethod
    def __len__(self) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...
    @classmethod
    def __setitem__(self, index, object) -> Any: ...

class EdgeVectorGridGraphUndirected2dMergeGraph(Boost.Python.instance):
    __instance_size__: Any = ...
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def append(self, *args, **kwargs) -> Any: ...
    @classmethod
    def extend(self, *args, **kwargs) -> Any: ...
    @classmethod
    def __contains__(self, other) -> Any: ...
    @classmethod
    def __delitem__(self, other) -> Any: ...
    @classmethod
    def __getitem__(self, index) -> Any: ...
    @classmethod
    def __iter__(self) -> Any: ...
    @classmethod
    def __len__(self) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...
    @classmethod
    def __setitem__(self, index, object) -> Any: ...

class EdgeVectorGridGraphUndirected3d(Boost.Python.instance):
    __instance_size__: Any = ...
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def append(self, *args, **kwargs) -> Any: ...
    @classmethod
    def extend(self, *args, **kwargs) -> Any: ...
    @classmethod
    def __contains__(self, other) -> Any: ...
    @classmethod
    def __delitem__(self, other) -> Any: ...
    @classmethod
    def __getitem__(self, index) -> Any: ...
    @classmethod
    def __iter__(self) -> Any: ...
    @classmethod
    def __len__(self) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...
    @classmethod
    def __setitem__(self, index, object) -> Any: ...

class EdgeVectorGridGraphUndirected3dMergeGraph(Boost.Python.instance):
    __instance_size__: Any = ...
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def append(self, *args, **kwargs) -> Any: ...
    @classmethod
    def extend(self, *args, **kwargs) -> Any: ...
    @classmethod
    def __contains__(self, other) -> Any: ...
    @classmethod
    def __delitem__(self, other) -> Any: ...
    @classmethod
    def __getitem__(self, index) -> Any: ...
    @classmethod
    def __iter__(self) -> Any: ...
    @classmethod
    def __len__(self) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...
    @classmethod
    def __setitem__(self, index, object) -> Any: ...

class GridGraphUndirected2d(Boost.Python.instance):
    edgeLengths: Any = ...
    mergeGraph: Any = ...
    nodeSize: Any = ...
    __instance_size__: Any = ...
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def affiliatedEdgesSerializationSize(self, *args, **kwargs) -> Any: ...
    @classmethod
    def arcFromId(self, *args, **kwargs) -> Any: ...
    @classmethod
    def arcIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def axistagsArcMap(self, *args, **kwargs) -> Any: ...
    @classmethod
    def axistagsEdgeMap(self, *args, **kwargs) -> Any: ...
    @classmethod
    def axistagsNodeMap(self, *args, **kwargs) -> Any: ...
    @classmethod
    def coordinateToNode(self, *args, **kwargs) -> Any: ...
    @classmethod
    def edgeFromArc(self, *args, **kwargs) -> Any: ...
    @classmethod
    def edgeFromId(self, *args, **kwargs) -> Any: ...
    @classmethod
    def edgeIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def edgeIter(self, *args, **kwargs) -> Any: ...
    @classmethod
    def findEdge(self, *args, **kwargs) -> Any: ...
    @classmethod
    def findEdges(self, *args, **kwargs) -> Any: ...
    @classmethod
    def id(self, *args, **kwargs) -> Any: ...
    @classmethod
    def incEdgeIter(self, *args, **kwargs) -> Any: ...
    @classmethod
    def intrinsicArcCoordinate(self, *args, **kwargs) -> Any: ...
    @classmethod
    def intrinsicArcMapShape(self, *args, **kwargs) -> Any: ...
    @classmethod
    def intrinsicEdgeCoordinate(self, *args, **kwargs) -> Any: ...
    @classmethod
    def intrinsicEdgeMapShape(self, *args, **kwargs) -> Any: ...
    @classmethod
    def intrinsicNodeCoordinate(self, *args, **kwargs) -> Any: ...
    @classmethod
    def intrinsicNodeMapShape(self, *args, **kwargs) -> Any: ...
    @classmethod
    def neighbourNodeIter(self, *args, **kwargs) -> Any: ...
    @classmethod
    def nodeFromId(self, *args, **kwargs) -> Any: ...
    @classmethod
    def nodeIdMap(self, *args, **kwargs) -> Any: ...
    @classmethod
    def nodeIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def nodeIter(self, *args, **kwargs) -> Any: ...
    @classmethod
    def source(self, *args, **kwargs) -> Any: ...
    @classmethod
    def target(self, *args, **kwargs) -> Any: ...
    @classmethod
    def u(self, *args, **kwargs) -> Any: ...
    @classmethod
    def uId(self, *args, **kwargs) -> Any: ...
    @classmethod
    def uIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def uvId(self, *args, **kwargs) -> Any: ...
    @classmethod
    def uvIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def v(self, *args, **kwargs) -> Any: ...
    @classmethod
    def vId(self, *args, **kwargs) -> Any: ...
    @classmethod
    def vIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def validArcIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def validEdgeIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def validNodeIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def __len__(self) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...
    @property
    def arcNum(self) -> Any: ...
    @property
    def edgeNum(self) -> Any: ...
    @property
    def maxArcId(self) -> Any: ...
    @property
    def maxEdgeId(self) -> Any: ...
    @property
    def maxNodeId(self) -> Any: ...
    @property
    def nodeNum(self) -> Any: ...
    @property
    def shape(self) -> Any: ...

class GridGraphUndirected2dMergeGraph(Boost.Python.instance):
    __instance_size__: Any = ...
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def arcFromId(self, *args, **kwargs) -> Any: ...
    @classmethod
    def arcIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def axistagsArcMap(self, *args, **kwargs) -> Any: ...
    @classmethod
    def axistagsEdgeMap(self, *args, **kwargs) -> Any: ...
    @classmethod
    def axistagsNodeMap(self, *args, **kwargs) -> Any: ...
    @classmethod
    def contractEdge(self, *args, **kwargs) -> Any: ...
    @classmethod
    def edgeFromArc(self, *args, **kwargs) -> Any: ...
    @classmethod
    def edgeFromId(self, *args, **kwargs) -> Any: ...
    @classmethod
    def edgeIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def edgeIter(self, *args, **kwargs) -> Any: ...
    @classmethod
    def findEdge(self, *args, **kwargs) -> Any: ...
    @classmethod
    def findEdges(self, *args, **kwargs) -> Any: ...
    @classmethod
    def graph(self, *args, **kwargs) -> Any: ...
    @classmethod
    def graphLabels(self, *args, **kwargs) -> Any: ...
    @classmethod
    def hasEdgeId(self, *args, **kwargs) -> Any: ...
    @classmethod
    def id(self, *args, **kwargs) -> Any: ...
    @classmethod
    def inactiveEdgesNode(self, *args, **kwargs) -> Any: ...
    @classmethod
    def incEdgeIter(self, *args, **kwargs) -> Any: ...
    @classmethod
    def intrinsicArcCoordinate(self, *args, **kwargs) -> Any: ...
    @classmethod
    def intrinsicArcMapShape(self, *args, **kwargs) -> Any: ...
    @classmethod
    def intrinsicEdgeCoordinate(self, *args, **kwargs) -> Any: ...
    @classmethod
    def intrinsicEdgeMapShape(self, *args, **kwargs) -> Any: ...
    @classmethod
    def intrinsicNodeCoordinate(self, *args, **kwargs) -> Any: ...
    @classmethod
    def intrinsicNodeMapShape(self, *args, **kwargs) -> Any: ...
    @classmethod
    def neighbourNodeIter(self, *args, **kwargs) -> Any: ...
    @classmethod
    def nodeFromId(self, *args, **kwargs) -> Any: ...
    @classmethod
    def nodeIdMap(self, *args, **kwargs) -> Any: ...
    @classmethod
    def nodeIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def nodeIter(self, *args, **kwargs) -> Any: ...
    @classmethod
    def source(self, *args, **kwargs) -> Any: ...
    @classmethod
    def target(self, *args, **kwargs) -> Any: ...
    @classmethod
    def u(self, *args, **kwargs) -> Any: ...
    @classmethod
    def uId(self, *args, **kwargs) -> Any: ...
    @classmethod
    def uIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def uvId(self, *args, **kwargs) -> Any: ...
    @classmethod
    def uvIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def v(self, *args, **kwargs) -> Any: ...
    @classmethod
    def vId(self, *args, **kwargs) -> Any: ...
    @classmethod
    def vIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def validArcIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def validEdgeIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def validNodeIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def __len__(self) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...
    @property
    def arcNum(self) -> Any: ...
    @property
    def edgeNum(self) -> Any: ...
    @property
    def maxArcId(self) -> Any: ...
    @property
    def maxEdgeId(self) -> Any: ...
    @property
    def maxNodeId(self) -> Any: ...
    @property
    def nodeNum(self) -> Any: ...

class GridGraphUndirected2dMergeGraphMinEdgeWeightNodeDistOperator(Boost.Python.instance):
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def enableStopWeight(self, *args, **kwargs) -> Any: ...
    @classmethod
    def setLiftedEdges(self, *args, **kwargs) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...

class GridGraphUndirected2dMergeGraphPythonOperator(Boost.Python.instance):
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def __reduce__(self) -> Any: ...

class GridGraphUndirected2dRagAffiliatedEdges(Boost.Python.instance):
    __instance_size__: Any = ...
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def getUVCoordinates(self, *args, **kwargs) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...

class GridGraphUndirected3d(Boost.Python.instance):
    edgeLengths: Any = ...
    mergeGraph: Any = ...
    nodeSize: Any = ...
    __instance_size__: Any = ...
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def affiliatedEdgesSerializationSize(self, *args, **kwargs) -> Any: ...
    @classmethod
    def arcFromId(self, *args, **kwargs) -> Any: ...
    @classmethod
    def arcIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def axistagsArcMap(self, *args, **kwargs) -> Any: ...
    @classmethod
    def axistagsEdgeMap(self, *args, **kwargs) -> Any: ...
    @classmethod
    def axistagsNodeMap(self, *args, **kwargs) -> Any: ...
    @classmethod
    def coordinateToNode(self, *args, **kwargs) -> Any: ...
    @classmethod
    def edgeFromArc(self, *args, **kwargs) -> Any: ...
    @classmethod
    def edgeFromId(self, *args, **kwargs) -> Any: ...
    @classmethod
    def edgeIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def edgeIter(self, *args, **kwargs) -> Any: ...
    @classmethod
    def findEdge(self, *args, **kwargs) -> Any: ...
    @classmethod
    def findEdges(self, *args, **kwargs) -> Any: ...
    @classmethod
    def id(self, *args, **kwargs) -> Any: ...
    @classmethod
    def incEdgeIter(self, *args, **kwargs) -> Any: ...
    @classmethod
    def intrinsicArcCoordinate(self, *args, **kwargs) -> Any: ...
    @classmethod
    def intrinsicArcMapShape(self, *args, **kwargs) -> Any: ...
    @classmethod
    def intrinsicEdgeCoordinate(self, *args, **kwargs) -> Any: ...
    @classmethod
    def intrinsicEdgeMapShape(self, *args, **kwargs) -> Any: ...
    @classmethod
    def intrinsicNodeCoordinate(self, *args, **kwargs) -> Any: ...
    @classmethod
    def intrinsicNodeMapShape(self, *args, **kwargs) -> Any: ...
    @classmethod
    def neighbourNodeIter(self, *args, **kwargs) -> Any: ...
    @classmethod
    def nodeFromId(self, *args, **kwargs) -> Any: ...
    @classmethod
    def nodeIdMap(self, *args, **kwargs) -> Any: ...
    @classmethod
    def nodeIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def nodeIter(self, *args, **kwargs) -> Any: ...
    @classmethod
    def source(self, *args, **kwargs) -> Any: ...
    @classmethod
    def target(self, *args, **kwargs) -> Any: ...
    @classmethod
    def u(self, *args, **kwargs) -> Any: ...
    @classmethod
    def uId(self, *args, **kwargs) -> Any: ...
    @classmethod
    def uIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def uvId(self, *args, **kwargs) -> Any: ...
    @classmethod
    def uvIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def v(self, *args, **kwargs) -> Any: ...
    @classmethod
    def vId(self, *args, **kwargs) -> Any: ...
    @classmethod
    def vIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def validArcIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def validEdgeIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def validNodeIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def __len__(self) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...
    @property
    def arcNum(self) -> Any: ...
    @property
    def edgeNum(self) -> Any: ...
    @property
    def maxArcId(self) -> Any: ...
    @property
    def maxEdgeId(self) -> Any: ...
    @property
    def maxNodeId(self) -> Any: ...
    @property
    def nodeNum(self) -> Any: ...
    @property
    def shape(self) -> Any: ...

class GridGraphUndirected3dMergeGraph(Boost.Python.instance):
    __instance_size__: Any = ...
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def arcFromId(self, *args, **kwargs) -> Any: ...
    @classmethod
    def arcIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def axistagsArcMap(self, *args, **kwargs) -> Any: ...
    @classmethod
    def axistagsEdgeMap(self, *args, **kwargs) -> Any: ...
    @classmethod
    def axistagsNodeMap(self, *args, **kwargs) -> Any: ...
    @classmethod
    def contractEdge(self, *args, **kwargs) -> Any: ...
    @classmethod
    def edgeFromArc(self, *args, **kwargs) -> Any: ...
    @classmethod
    def edgeFromId(self, *args, **kwargs) -> Any: ...
    @classmethod
    def edgeIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def edgeIter(self, *args, **kwargs) -> Any: ...
    @classmethod
    def findEdge(self, *args, **kwargs) -> Any: ...
    @classmethod
    def findEdges(self, *args, **kwargs) -> Any: ...
    @classmethod
    def graph(self, *args, **kwargs) -> Any: ...
    @classmethod
    def graphLabels(self, *args, **kwargs) -> Any: ...
    @classmethod
    def hasEdgeId(self, *args, **kwargs) -> Any: ...
    @classmethod
    def id(self, *args, **kwargs) -> Any: ...
    @classmethod
    def inactiveEdgesNode(self, *args, **kwargs) -> Any: ...
    @classmethod
    def incEdgeIter(self, *args, **kwargs) -> Any: ...
    @classmethod
    def intrinsicArcCoordinate(self, *args, **kwargs) -> Any: ...
    @classmethod
    def intrinsicArcMapShape(self, *args, **kwargs) -> Any: ...
    @classmethod
    def intrinsicEdgeCoordinate(self, *args, **kwargs) -> Any: ...
    @classmethod
    def intrinsicEdgeMapShape(self, *args, **kwargs) -> Any: ...
    @classmethod
    def intrinsicNodeCoordinate(self, *args, **kwargs) -> Any: ...
    @classmethod
    def intrinsicNodeMapShape(self, *args, **kwargs) -> Any: ...
    @classmethod
    def neighbourNodeIter(self, *args, **kwargs) -> Any: ...
    @classmethod
    def nodeFromId(self, *args, **kwargs) -> Any: ...
    @classmethod
    def nodeIdMap(self, *args, **kwargs) -> Any: ...
    @classmethod
    def nodeIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def nodeIter(self, *args, **kwargs) -> Any: ...
    @classmethod
    def source(self, *args, **kwargs) -> Any: ...
    @classmethod
    def target(self, *args, **kwargs) -> Any: ...
    @classmethod
    def u(self, *args, **kwargs) -> Any: ...
    @classmethod
    def uId(self, *args, **kwargs) -> Any: ...
    @classmethod
    def uIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def uvId(self, *args, **kwargs) -> Any: ...
    @classmethod
    def uvIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def v(self, *args, **kwargs) -> Any: ...
    @classmethod
    def vId(self, *args, **kwargs) -> Any: ...
    @classmethod
    def vIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def validArcIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def validEdgeIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def validNodeIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def __len__(self) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...
    @property
    def arcNum(self) -> Any: ...
    @property
    def edgeNum(self) -> Any: ...
    @property
    def maxArcId(self) -> Any: ...
    @property
    def maxEdgeId(self) -> Any: ...
    @property
    def maxNodeId(self) -> Any: ...
    @property
    def nodeNum(self) -> Any: ...

class GridGraphUndirected3dMergeGraphMinEdgeWeightNodeDistOperator(Boost.Python.instance):
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def enableStopWeight(self, *args, **kwargs) -> Any: ...
    @classmethod
    def setLiftedEdges(self, *args, **kwargs) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...

class GridGraphUndirected3dMergeGraphPythonOperator(Boost.Python.instance):
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def __reduce__(self) -> Any: ...

class GridGraphUndirected3dRagAffiliatedEdges(Boost.Python.instance):
    __instance_size__: Any = ...
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def getUVCoordinates(self, *args, **kwargs) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...

class GridRegionAdjacencyGraph(RegionAdjacencyGraph):
    __init__: Any = ...
    edgeLengths: Any = ...
    nodeSize: Any = ...
    projectLabelsToGridGraph: Any = ...
    projectNodeFeaturesToGridGraph: Any = ...
    show: Any = ...
    showEdgeFeature: Any = ...
    showNested: Any = ...
    writeHDF5: Any = ...
    @property
    def shape(self) -> Any: ...

class HierarchicalClusteringAdjacencyListGraphMergeGraphMinEdgeWeightNodeDistOperator(Boost.Python.instance):
    __instance_size__: Any = ...
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def cluster(self, *args, **kwargs) -> Any: ...
    @classmethod
    def reprNodeIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def resultLabels(self, *args, **kwargs) -> Any: ...
    @classmethod
    def ucmTransform(self, *args, **kwargs) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...

class HierarchicalClusteringAdjacencyListGraphMergeGraphPythonOperator(Boost.Python.instance):
    __instance_size__: Any = ...
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def cluster(self, *args, **kwargs) -> Any: ...
    @classmethod
    def reprNodeIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def resultLabels(self, *args, **kwargs) -> Any: ...
    @classmethod
    def ucmTransform(self, *args, **kwargs) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...

class HierarchicalClusteringGridGraphUndirected2dMergeGraphMinEdgeWeightNodeDistOperator(Boost.Python.instance):
    __instance_size__: Any = ...
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def cluster(self, *args, **kwargs) -> Any: ...
    @classmethod
    def reprNodeIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def resultLabels(self, *args, **kwargs) -> Any: ...
    @classmethod
    def ucmTransform(self, *args, **kwargs) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...

class HierarchicalClusteringGridGraphUndirected2dMergeGraphPythonOperator(Boost.Python.instance):
    __instance_size__: Any = ...
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def cluster(self, *args, **kwargs) -> Any: ...
    @classmethod
    def reprNodeIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def resultLabels(self, *args, **kwargs) -> Any: ...
    @classmethod
    def ucmTransform(self, *args, **kwargs) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...

class HierarchicalClusteringGridGraphUndirected3dMergeGraphMinEdgeWeightNodeDistOperator(Boost.Python.instance):
    __instance_size__: Any = ...
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def cluster(self, *args, **kwargs) -> Any: ...
    @classmethod
    def reprNodeIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def resultLabels(self, *args, **kwargs) -> Any: ...
    @classmethod
    def ucmTransform(self, *args, **kwargs) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...

class HierarchicalClusteringGridGraphUndirected3dMergeGraphPythonOperator(Boost.Python.instance):
    __instance_size__: Any = ...
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def cluster(self, *args, **kwargs) -> Any: ...
    @classmethod
    def reprNodeIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def resultLabels(self, *args, **kwargs) -> Any: ...
    @classmethod
    def ucmTransform(self, *args, **kwargs) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...

class ImplicitMEanEdgeMap_2d_float_float(Boost.Python.instance):
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def __reduce__(self) -> Any: ...

class ImplicitMEanEdgeMap_3d_float_float(Boost.Python.instance):
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def __reduce__(self) -> Any: ...

class IncEdgeIteratorHolderAdjacencyListGraph(Boost.Python.instance):
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def __iter__(self) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...

class IncEdgeIteratorHolderAdjacencyListGraphMergeGraph(Boost.Python.instance):
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def __iter__(self) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...

class IncEdgeIteratorHolderGridGraphUndirected2d(Boost.Python.instance):
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def __iter__(self) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...

class IncEdgeIteratorHolderGridGraphUndirected2dMergeGraph(Boost.Python.instance):
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def __iter__(self) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...

class IncEdgeIteratorHolderGridGraphUndirected3d(Boost.Python.instance):
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def __iter__(self) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...

class IncEdgeIteratorHolderGridGraphUndirected3dMergeGraph(Boost.Python.instance):
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def __iter__(self) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...

class Invalid(Boost.Python.instance):
    __instance_size__: Any = ...
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def __reduce__(self) -> Any: ...

class MetricType(Boost.Python.enum):
    bhattacharya: Any = ...
    chiSquared: Any = ...
    hellinger: Any = ...
    manhattan: Any = ...
    names: Any = ...
    norm: Any = ...
    squaredNorm: Any = ...
    symetricKl: Any = ...
    values: Any = ...
    __slots__: Any = ...

class NeighbourNodeIteratorHolderAdjacencyListGraph(Boost.Python.instance):
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def __iter__(self) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...

class NeighbourNodeIteratorHolderAdjacencyListGraphMergeGraph(Boost.Python.instance):
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def __iter__(self) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...

class NeighbourNodeIteratorHolderGridGraphUndirected2d(Boost.Python.instance):
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def __iter__(self) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...

class NeighbourNodeIteratorHolderGridGraphUndirected2dMergeGraph(Boost.Python.instance):
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def __iter__(self) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...

class NeighbourNodeIteratorHolderGridGraphUndirected3d(Boost.Python.instance):
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def __iter__(self) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...

class NeighbourNodeIteratorHolderGridGraphUndirected3dMergeGraph(Boost.Python.instance):
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def __iter__(self) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...

class NodeAdjacencyListGraph(Boost.Python.instance):
    __instance_size__: Any = ...
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def coord(self, *args, **kwargs) -> Any: ...
    @classmethod
    def __eq__(self, other) -> Any: ...
    @classmethod
    def __ne__(self, other) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...
    @property
    def id(self) -> Any: ...

class NodeAdjacencyListGraphMergeGraph(Boost.Python.instance):
    __instance_size__: Any = ...
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def coord(self, *args, **kwargs) -> Any: ...
    @classmethod
    def __eq__(self, other) -> Any: ...
    @classmethod
    def __ne__(self, other) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...
    @property
    def id(self) -> Any: ...

class NodeGridGraphUndirected2d(Boost.Python.instance):
    __instance_size__: Any = ...
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def coord(self, *args, **kwargs) -> Any: ...
    @classmethod
    def __eq__(self, other) -> Any: ...
    @classmethod
    def __ne__(self, other) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...
    @property
    def id(self) -> Any: ...

class NodeGridGraphUndirected2dMergeGraph(Boost.Python.instance):
    __instance_size__: Any = ...
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def coord(self, *args, **kwargs) -> Any: ...
    @classmethod
    def __eq__(self, other) -> Any: ...
    @classmethod
    def __ne__(self, other) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...
    @property
    def id(self) -> Any: ...

class NodeGridGraphUndirected3d(Boost.Python.instance):
    __instance_size__: Any = ...
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def coord(self, *args, **kwargs) -> Any: ...
    @classmethod
    def __eq__(self, other) -> Any: ...
    @classmethod
    def __ne__(self, other) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...
    @property
    def id(self) -> Any: ...

class NodeGridGraphUndirected3dMergeGraph(Boost.Python.instance):
    __instance_size__: Any = ...
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def coord(self, *args, **kwargs) -> Any: ...
    @classmethod
    def __eq__(self, other) -> Any: ...
    @classmethod
    def __ne__(self, other) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...
    @property
    def id(self) -> Any: ...

class NodeIteratorHolderAdjacencyListGraph(Boost.Python.instance):
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def __iter__(self) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...

class NodeIteratorHolderAdjacencyListGraphMergeGraph(Boost.Python.instance):
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def __iter__(self) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...

class NodeIteratorHolderGridGraphUndirected2d(Boost.Python.instance):
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def __iter__(self) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...

class NodeIteratorHolderGridGraphUndirected2dMergeGraph(Boost.Python.instance):
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def __iter__(self) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...

class NodeIteratorHolderGridGraphUndirected3d(Boost.Python.instance):
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def __iter__(self) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...

class NodeIteratorHolderGridGraphUndirected3dMergeGraph(Boost.Python.instance):
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def __iter__(self) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...

class RegionAdjacencyGraph(AdjacencyListGraph):
    __init__: Any = ...
    accumulateEdgeFeatures: Any = ...
    accumulateEdgeStatistics: Any = ...
    accumulateNodeFeatures: Any = ...
    accumulateSeeds: Any = ...
    edgeCoordinates: Any = ...
    edgeTopologicalCoordinates: Any = ...
    edgeUVCoordinates: Any = ...
    mergeGraph: Any = ...
    projectBaseGraphGt: Any = ...
    projectLabelsBack: Any = ...
    projectLabelsToBaseGraph: Any = ...
    projectNodeFeatureToBaseGraph: Any = ...

class ShortestPathDijkstraAdjacencyListGraph(Boost.Python.instance):
    __instance_size__: Any = ...
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def distance(self, *args, **kwargs) -> Any: ...
    @classmethod
    def distances(self, *args, **kwargs) -> Any: ...
    @classmethod
    def nodeCoordinatePath(self, *args, **kwargs) -> Any: ...
    @classmethod
    def nodeIdPath(self, *args, **kwargs) -> Any: ...
    @classmethod
    def predecessors(self, *args, **kwargs) -> Any: ...
    @classmethod
    def run(self, *args, **kwargs) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...

class ShortestPathDijkstraGridGraphUndirected2d(Boost.Python.instance):
    __instance_size__: Any = ...
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def distance(self, *args, **kwargs) -> Any: ...
    @classmethod
    def distances(self, *args, **kwargs) -> Any: ...
    @classmethod
    def nodeCoordinatePath(self, *args, **kwargs) -> Any: ...
    @classmethod
    def nodeIdPath(self, *args, **kwargs) -> Any: ...
    @classmethod
    def predecessors(self, *args, **kwargs) -> Any: ...
    @classmethod
    def run(self, *args, **kwargs) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...

class ShortestPathDijkstraGridGraphUndirected3d(Boost.Python.instance):
    __instance_size__: Any = ...
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def distance(self, *args, **kwargs) -> Any: ...
    @classmethod
    def distances(self, *args, **kwargs) -> Any: ...
    @classmethod
    def nodeCoordinatePath(self, *args, **kwargs) -> Any: ...
    @classmethod
    def nodeIdPath(self, *args, **kwargs) -> Any: ...
    @classmethod
    def predecessors(self, *args, **kwargs) -> Any: ...
    @classmethod
    def run(self, *args, **kwargs) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...

class ShortestPathPathDijkstra:
    __init__: Any = ...
    distance: Any = ...
    distances: Any = ...
    path: Any = ...
    predecessors: Any = ...
    run: Any = ...
    runIgnoreLargeWeights: Any = ...

class TinyEdgeLabelGui:
    __init__: Any = ...
    handle_click: Any = ...
    on_motion: Any = ...
    on_release: Any = ...
    onclick: Any = ...
    press_event: Any = ...
    scroll: Any = ...
    slice2d: Any = ...
    startGui: Any = ...
    updateBrushSize: Any = ...
