gaussianHistogram: Any
gaussianRankOrder: Any

def _gaussianRankOrder(*args, **kwargs) -> Any: ...
def gaussianCoHistogram(*args, **kwargs) -> Any: ...
def gaussianHistogram_(*args, **kwargs) -> Any: ...
