def linearNoiseNormalization(*args, **kwargs) -> Any: ...
def linearNoiseNormalizationEstimated(*args, **kwargs) -> Any: ...
def noiseVarianceClustering(*args, **kwargs) -> Any: ...
def noiseVarianceEstimation(*args, **kwargs) -> Any: ...
def nonparametricNoiseNormalization(*args, **kwargs) -> Any: ...
def quadraticNoiseNormalization(*args, **kwargs) -> Any: ...
def quadraticNoiseNormalizationEstimated(*args, **kwargs) -> Any: ...
