def lassoRegression(*args, **kwargs) -> Any: ...
def leastSquares(*args, **kwargs) -> Any: ...
def nonnegativeLeastSquares(*args, **kwargs) -> Any: ...
def ridgeRegression(*args, **kwargs) -> Any: ...
