"""
This type stub file was generated by pyright.
"""

from .file import File, N5File, S3File, ZarrFile
from .dataset import Dataset
from .group import Group
from .attribute_manager import set_json_decoder, set_json_encoder

__version__ = "2.0.9"
__version_info__ = tuple(int(i) for i in __version__.split("."))
