"""
This type stub file was generated by pyright.
"""

from collections.abc import MutableMapping

_JSON_ENCODER = None
_JSON_DECODER = None
def set_json_encoder(encoder):
    """ Set the encoder to be used in `json.dump` for attribute serialization.
    """
    ...

def get_json_encoder():
    ...

def set_json_decoder(decoder):
    """ Set the decoder to be used in `json.load` for attribute de-serialization.
    """
    ...

class AttributeManager(MutableMapping):
    """ Provides access to custom user attributes.

    Attributes will be saved as json in `attributes.json` for n5, `.zattributes` for zarr.
    Supports the default python dict api.
    N5 stores the dataset attributes in the same file; these attributes are
    NOT mutable via the AttributeManager.
    """
    def __init__(self, handle) -> None:
        ...
    
    def __getitem__(self, key):
        ...
    
    def __setitem__(self, key, item):
        ...
    
    def __delitem__(self, key):
        ...
    
    def __iter__(self):
        ...
    
    def __len__(self):
        ...
    


