#!/bin/bash
set -u
set -e
set -x

MASTER_USER="${MASTER_USER}"
MASTER_IP="${MASTER_IP}"
SOCKET_PATH_AT_MASTER="${SOCKET_PATH_AT_MASTER}"
SOCKET_PATH_AT_WORKER="${SOCKET_PATH_AT_WORKER}"
SOCKET_PATH_AT_WORKER="${SOCKET_PATH_AT_WORKER}"


rm -fv "${SOCKET_PATH_AT_WORKER}"
nc -lkU "${SOCKET_PATH_AT_WORKER}" &

ssh "${MASTER_USER}@${MASTER_IP}" -- rm -fv "$SOCKET_PATH_AT_MASTER"
ssh -R "${SOCKET_PATH_AT_MASTER}:${SOCKET_PATH_AT_WORKER}" "${MASTER_USER}@${MASTER_IP}" -N
